### PR TITLE
Add LayerNamesAttribute to generate layer names from the project.

### PR DESCRIPTION
**Pull request by qwe321qwe321qwe321**
Hello, I added a new attribute `[LayerNames]` which is pretty similar to the `[InputMap]` feature.

## Usage
For exmaple, there are some layers defined in the project.
image

Add a new script with the `[LayerNames]` attribute.
```cs
using Godot;

[LayerNames]
public static partial class LayerGen { }
```
It generates the code:

```cs
using System;
using System.ComponentModel;

using Godot;

partial class LayerGen
{
    public static class Render2D
    {
        public const int Layer1 = 0;
        public const uint Layer1_Mask = 1u << 0;
        public const int Layer2 = 1;
        public const uint Layer2_Mask = 1u << 1;
        public const int Layer7 = 6;
        public const uint Layer7_Mask = 1u << 6;
        public const int _11Layer = 10;
        public const uint _11Layer_Mask = 1u << 10;
    }
    public static class Render3D
    {
        public const int Layer11 = 10;
        public const uint Layer11_Mask = 1u << 10;
        // ...
    }
    // ...Physics2D, Navigation2D, Physics3D, Navigation3D, and Avoidance classes.
}
```

This PR is a draft, as I need to ask if you want this feature to merge. At least it is very useful to me.
But also issue #57 bothers me to test it on the latest commit, so I think it should be a draft at least for now.

Oh, and I haven't updated README yet. I will do that if you think this PR is valid.

### CODE REVIEW

**Comment by Cat-Lips** [comment]
Nice idea.  Definitely worth including. :)

**Comment by qwe321qwe321qwe321** [comment]
@Cat-Lips  Just to confirm. I made this attribute based on how your `InputMapAttribute` did. And I noticed that there was a class `Diagnostics` which is not used at all. It looks like the legacy code which is not needed, right?

```cs
namespace GodotSharp.SourceGenerators.InputMapExtensions
{
    internal static class Diagnostics
    {
        public static DiagnosticDetail GodotAttributeNotFound(string tscn) => new() { Title = "Scene file not found", Message = $"Could not find scene file: {tscn}" };
    }
}
```

**Comment by Cat-Lips** [comment]
> @Cat-Lips Just to confirm. I made this attribute based on how your `InputMapAttribute` did. And I noticed that there was a class `Diagnostics` which is not used at all. It looks like the legacy code which is not needed, right? I am not gonna change that but will not include that in my `LayerNamesAttribute`
> 
> ```cs
> namespace GodotSharp.SourceGenerators.InputMapExtensions
> {
>     internal static class Diagnostics
>     {
>         public static DiagnosticDetail GodotAttributeNotFound(string tscn) => new() { Title = "Scene file not found", Message = $"Could not find scene file: {tscn}" };
>     }
> }
> ```

Yes, Diagnostics is only needed for generators that need to report errors.  It should be removed if not needed.

**Comment by qwe321qwe321qwe321** [comment]
OK, the PR is ready.
The last commit is to support the unicode naming and the names with space characters.

For example
image

`project.godot` looks like:
```
[layer_names]

2d_physics/layer_4="layer 4"
2d_physics/layer_5="layer5"
2d_physics/layer_6="there is the space"
2d_physics/layer_9="there_is_no_space"
2d_physics/layer_10="中文\".\\/'?"
```

The generated code will be:
```cs
partial class Layers
{
    public static class Physics2D
    {
        public const int Layer4 = 3;
        public const uint Layer4_Mask = 1u << 3;
        public const int Layer5 = 4;
        public const uint Layer5_Mask = 1u << 4;
        public const int ThereIsTheSpace = 5;
        public const uint ThereIsTheSpace_Mask = 1u << 5;
        public const int ThereIsNoSpace = 8;
        public const uint ThereIsNoSpace_Mask = 1u << 8;
        public const int _中文_ = 9;
        public const uint _中文__Mask = 1u << 9;
    }
}
```

**Comment by Cat-Lips** [comment]
Just fyi, I'll release 2.3.4 then this can be included in 2.4.0

We will also need to add your local tests to the test runner :)

**Comment by qwe321qwe321qwe321** [comment]
> We will also need to add your local tests to the test runner :)
I didn't quite understand the test flow in this repo yet.
Since this feature depends on the godot project setting, should I directly modify the project setting and add a test in `TestScene/`? (I couldn't find the `[InputMap]` test, which could be a good reference to me.)

And since the Test projects couldn't refer the local nuget build automatically (The package version in csproj won't fit the local package as the local version number updated every time.) I tested the feature by always manually putting the exported dll to .nuget folder inside the Test project. 
Is there other setup I should do for this PR? I guess you will update the Nuget package for Test.csproj?

**Comment by Cat-Lips** [comment]
Ah, true.  I couldn't find any InputMap tests either.
I'll have to fix that for next release and I can add some for layers at the same time.

Ok, so nice work on this.  Let's get it merged :D
(I've created a new issue and branch.  I'll merge it there so I can tinker with tests.)

**Comment by Cat-Lips** [comment]
Hey PeDev,

All done.  Mostly the same, I just made a nested Mask class inside each layer class.
Tests added, docs updated, pre-release nuget uploaded.
Let me know if there's anything else.

Cheers :)

**Comment by qwe321qwe321qwe321** [comment]
> All done. Mostly the same, I just made a nested Mask class inside each layer class.
> Tests added, docs updated, pre-release nuget uploaded.
> Let me know if there's anything else.
Thanks! I was about to ask the Mask design. I was worried if the nested Mask would be too long to write. But it seems pretty good now :)

**Pull request merged**
