### PR TITLE
Add Autoload class attribute for static typing of project autoloads

### PR DESCRIPTION
**Pull request by jwright159**
This is my first time touching source generators so I copied InputMapExtensions + SceneTreeExtensions. It generates references to project autoloads

~~Also sorry I didn't add any tests :T~~

### CODE REVIEW

**Comment by Cat-Lips** [comment]
Great idea.  In C#, I normally use Singletons or statics instead of Autoloads, but this is a nice way of doing it.  I'll add an enhancement issue and "borrow" from this PR if that's ok.

**Comment by Cat-Lips** [comment]
Added some tests to new issue/branch.  Edge cases will require parsing of tscn to get script and correct type.  Current usage also requires the node to be inside tree (as looks to be the case for gdscript also).

https://github.com/Cat-Lips/GodotSharp.SourceGenerators/issues/49

It might be more simple for each autoload to have a static Instance property, set when autoload is first created by Godot (ie, Instance ??= this; in autoload constructor).

Let me know what you think.

Cheers.

**Comment by jwright159** [comment]
Ohhh yeah, giving autoloads Instance properties would definitely be more C#-like. As well as just being simpler

**Comment by Cat-Lips** [comment]
Ok.  I'll close this, but a helpful experiment nonetheless.

**Pull request closed without merging**
